allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: set this to true or false
  core-js: true
  esbuild: set this to true or false
  prisma: true
  unrs-resolver: set this to true or false
